Blogistaan/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Blogistaan.Controllers
{
    public class AccountsController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult AdminLogin()
        {
            return View();
        }

       

    }
}

Blogistaan/Controllers/LoginController.cs
using Blogistaan.Models;
using Blogistaan.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Blogistaan.Controllers
{
    public class LoginController : Controller
    {

        [HttpGet]
        public IActionResult WriterLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult WriterLogin(Writer writerobj)
        {

            // Your login validation logic

            //if (loginSuccess)
            //{
            //    // Successful login logic
            //    return RedirectToAction("Index", "Home");
            //}
           

            var writerrepo = new WriterRepo();
            int id = writerrepo.ValidateWriterLogin(writerobj.Username, writerobj.Password);
            if (id!=0)
            {
                HttpContext.Response.Cookies.Append("WriterId", id.ToString());

                return RedirectToAction("Dashboard", "Writer");

            }

            else
            {
                ViewBag.InvalidCredentials = true;
                //ModelState.AddModelError("", "Invalid credentials. Please try again.");
                return View();
                //return View();

            }


        }

        [HttpGet]
        public IActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AdminLogin(Admin adminobj)
        {

            var adminrepo = new AdminRepo();
            int id = adminrepo.ValidateAdminLogin(adminobj.Username, adminobj.Password);
            if (id!=0)
            {
                HttpContext.Response.Cookies.Append("AdminId", id.ToString());

                return RedirectToAction("Dashboard", "Admin");

            }
            

            else
            {
                ViewBag.InvalidCredentials = true;
                //ModelState.AddModelError("", "Invalid credentials. Please try again.");
                //return View(admin);
                return View();

            }

        }

       

    }
}

Blogistaan/Views/Accounts/AdminLogin.cshtml
@model Blogistaan.Models.Admin

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@{
    ViewBag.Title = "Admin Login";
}

<div class="container my-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>Admin Login</h2>
            @Html.ValidationSummary()
            @using (Html.BeginForm("AdminLogin", "Accounts", FormMethod.Post, new { @class = "form" }))
            {
                <div class="form-group">
                    @Html.LabelFor(m => m.Username)
                    @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Username)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password)
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            }
        </div>
    </div>
</div>

Blogistaan/Views/Accounts/Login.cshtml
@model Blogistaan.Models.User

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewBag.Title = "User Login";
}

<div class="container my-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>User Login</h2>
            @Html.ValidationSummary()
            @using (Html.BeginForm("UserLogin", "Account", FormMethod.Post, new { @class = "form" }))
            {
                <div class="form-group">
                    @Html.LabelFor(m => m.Username)
                    @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Username)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password)
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
                <a href="@Url.Action("AdminLogin", "Accounts")" class="btn btn-link">Admin Login</a>
            }
        </div>
    </div>
</div>