Blogistaan/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;

namespace Blogistaan.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Chat()
        {
            return View();
        }
    }
}

Blogistaan/Controllers/LoginController.cs
using Blogistaan.Models;
using Blogistaan.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Blogistaan.Controllers
{
    public class LoginController : Controller
    {

        [HttpGet]
        public IActionResult WriterLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult WriterLogin(Writer writerobj)
        {

            // Your login validation logic

            //if (loginSuccess)
            //{
            //    // Successful login logic
            //    return RedirectToAction("Index", "Home");
            //}
           

            var writerrepo = new WriterRepo();
            int id = writerrepo.ValidateWriterLogin(writerobj.Username, writerobj.Password);
            if (id!=0)
            {
                HttpContext.Response.Cookies.Append("WriterId", id.ToString());

                return RedirectToAction("Dashboard", "Writer");

            }

            else
            {
                ViewBag.InvalidCredentials = true;
                //ModelState.AddModelError("", "Invalid credentials. Please try again.");
                return View();
                //return View();

            }


        }

        [HttpGet]
        public IActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AdminLogin(Admin adminobj)
        {

            var adminrepo = new AdminRepo();
            int id = adminrepo.ValidateAdminLogin(adminobj.Username, adminobj.Password);
            if (id!=0)
            {
                HttpContext.Response.Cookies.Append("AdminId", id.ToString());

                return RedirectToAction("Dashboard", "Admin");

            }
            

            else
            {
                ViewBag.InvalidCredentials = true;
                //ModelState.AddModelError("", "Invalid credentials. Please try again.");
                //return View(admin);
                return View();

            }

        }

       

    }
}

Blogistaan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewData["Title"] - Blogistaan</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    </head>

    <body>

       @* <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Home">Blogistaan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Login" asp-action="WriterLogin">Login</a>
                    </li>

                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Writer" asp-action="Dashboard">Writer Dashboard</a>
                </li>

                  
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Dashboard">Admin Dashboard</a>
                </li>

                </ul>
            </div>
        </nav>
                *@

            
        @Html.Partial("_Menubar")

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>
        </div>

    <footer>
        <div class="container-fluid bg-dark text-light py-3">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Home">
                            Blogistaan &copy; 2023
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
        <!-- Bootstrap JavaScript and jQuery-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

        @*    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper-base.min.js"></script>
        *@    

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("Scripts", required: false)
    </body>

    
</html>

Blogistaan/Views/Shared/_Menubar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Home">Blogistaan</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Chat" asp-action="Chat">Hangout</a>
            </li>

@*
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>*@

           @* <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="WriterLogin">Login</a>
            </li>*@

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Writer" asp-action="Dashboard">Writer Dashboard</a>
            </li>


            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Dashboard">Admin Dashboard</a>
            </li>

        </ul>
    </div>
</nav>